# Default configuration for ding.runner.inpaint_vid_dataset

defaults:
  - _self_

seed: 42
device: cuda:0
model_dtype: bfloat16

dataset_dir: /path/to/inpaint_video_dataset
metadata_file: ${dataset_dir}/metadata.json
dilate_mask: true   
output_dir: /path/to/output_dir
steps: 45
show_progress: true

denoiser:
  name: ltx
  params:
    model_cpu_offload: false      # choose either model_cpu_offload or sequential_cpu_offload
    sequential_cpu_offload: false
    attention_slicing: false
    vae_slicing: false
  cache_dir: null                 # path to cache the denoiser model, if null it will use the default huggingface cache dir
 
sampler:
  name: ding

conditioning:
  negative_prompts: ""
  guidance_scale: 3.5
  guidance_rescale: 0.0
  n_videos_per_prompt: 1

video:
  target_height: 512              # multiple of 32 if set
  target_width: 928               # multiple of 32 if set
  target_num_frames: 97           # or 121 ==> (target_num_frames-1) multiple of 8, and inf or equal (n_frames: (n_seconds * fps) + 1)   
  frame_rate: 24                  # Target frame rate for denoiser setup and output export


